### ISSUE TITLE
v3.5.1 missing

### ISSUE THREAD

**Issue by ZLLentz** [conda-forge/line_profiler-feedstock#54]
### Comment:

Hi, I noticed that v3.5.0 and v3.5.1 never got built for this feedstock. Was there a problem with these, or did the bot get stuck and never make the PR?

**Comment by jakirkham** [comment]
Yeah upstream didn't push `sdist`s for these. So the autoupdate bot never picked them up. Raised upstream issue ( https://github.com/pyutils/line_profiler/issues/148 ) about publishing these `sdist`s

**Comment by jakirkham** [comment]
Since there were build issues in that version that could not be resolved, we are skipping it in favor of 4.0.x

**Comment by jakirkham** [comment]
Packages for 4.0.1 are built and uploaded. Please see PR ( https://github.com/conda-forge/line_profiler-feedstock/pull/66 ) for relevant changes
